import type { CartItem } from "@/contexts/ProjectCartContext";

interface PdfExportData {
  items: CartItem[];
  formData: { name: string; company: string; email: string; phone: string };
  totalBudget: number;
  notes: string;
  lang: string;
}

/** Labels per language */
const labels: Record<string, Record<string, string>> = {
  en: {
    title: "Project Quotation Request",
    ref: "Ref",
    date: "Date",
    clientInfo: "Client Information",
    name: "Name",
    company: "Company",
    email: "Email",
    phone: "Phone",
    productTable: "Product Selection",
    col_num: "#",
    col_product: "Product",
    col_category: "Category",
    col_qty: "Qty",
    col_unit_price: "Unit Price",
    col_total: "Total",
    subtotal: "Subtotal",
    onRequest: "On request",
    budgetSummary: "Budget Summary",
    totalEstimated: "Total Estimated Budget",
    numProducts: "Number of Products",
    numSuppliers: "Suppliers Selected",
    notes: "Notes",
    footer: "Generated by Terrassea — B2B Outdoor Furniture Sourcing",
    exclVat: "Excl. delivery & VAT — indicative pricing",
  },
  fr: {
    title: "Demande de Devis Projet",
    ref: "Réf",
    date: "Date",
    clientInfo: "Informations Client",
    name: "Nom",
    company: "Entreprise",
    email: "Email",
    phone: "Téléphone",
    productTable: "Sélection Produits",
    col_num: "#",
    col_product: "Produit",
    col_category: "Catégorie",
    col_qty: "Qté",
    col_unit_price: "Prix unit.",
    col_total: "Total",
    subtotal: "Sous-total",
    onRequest: "Sur demande",
    budgetSummary: "Récapitulatif Budget",
    totalEstimated: "Budget Total Estimé",
    numProducts: "Nombre de Produits",
    numSuppliers: "Fournisseurs Sélectionnés",
    notes: "Notes",
    footer: "Généré par Terrassea — Sourcing Mobilier Outdoor B2B",
    exclVat: "Hors livraison & TVA — tarifs indicatifs",
  },
  es: {
    title: "Solicitud de Presupuesto",
    ref: "Ref",
    date: "Fecha",
    clientInfo: "Información del Cliente",
    name: "Nombre",
    company: "Empresa",
    email: "Email",
    phone: "Teléfono",
    productTable: "Selección de Productos",
    col_num: "#",
    col_product: "Producto",
    col_category: "Categoría",
    col_qty: "Cant.",
    col_unit_price: "Precio unit.",
    col_total: "Total",
    subtotal: "Subtotal",
    onRequest: "Bajo consulta",
    budgetSummary: "Resumen del Presupuesto",
    totalEstimated: "Presupuesto Total Estimado",
    numProducts: "Número de Productos",
    numSuppliers: "Proveedores Seleccionados",
    notes: "Notas",
    footer: "Generado por Terrassea — Sourcing Mobiliario Outdoor B2B",
    exclVat: "Sin envío ni IVA — precios indicativos",
  },
  it: {
    title: "Richiesta di Preventivo",
    ref: "Rif",
    date: "Data",
    clientInfo: "Informazioni Cliente",
    name: "Nome",
    company: "Azienda",
    email: "Email",
    phone: "Telefono",
    productTable: "Selezione Prodotti",
    col_num: "#",
    col_product: "Prodotto",
    col_category: "Categoria",
    col_qty: "Qtà",
    col_unit_price: "Prezzo unit.",
    col_total: "Totale",
    subtotal: "Subtotale",
    onRequest: "Su richiesta",
    budgetSummary: "Riepilogo Budget",
    totalEstimated: "Budget Totale Stimato",
    numProducts: "Numero di Prodotti",
    numSuppliers: "Fornitori Selezionati",
    notes: "Note",
    footer: "Generato da Terrassea — Sourcing Arredamento Outdoor B2B",
    exclVat: "Esclusa consegna e IVA — prezzi indicativi",
  },
};

function getProductName(item: CartItem, lang: string): string {
  const p = item.product;
  if (lang === "fr" && p.name_fr) return p.name_fr;
  if (lang === "es" && p.name_es) return p.name_es;
  if (lang === "it" && p.name_it) return p.name_it;
  return p.name;
}

function generateRefNumber(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let ref = "TRS-";
  for (let i = 0; i < 8; i++) {
    ref += chars[Math.floor(Math.random() * chars.length)];
  }
  return ref;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function exportCartAsPdf(data: PdfExportData): void {
  const { items, formData, totalBudget, notes, lang } = data;
  const l = labels[lang] || labels.en;
  const ref = generateRefNumber();
  const now = new Date();
  const dateStr = now.toLocaleDateString(lang === "fr" ? "fr-FR" : lang === "es" ? "es-ES" : lang === "it" ? "it-IT" : "en-GB", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Group items by concept
  const grouped: Record<string, CartItem[]> = {};
  for (const item of items) {
    const key = item.conceptName || "—";
    if (!grouped[key]) grouped[key] = [];
    grouped[key].push(item);
  }

  const suppliersSelected = items.filter((i) => i.selectedSupplier).length;

  // Build product rows
  let rowIndex = 0;
  let tableHtml = "";

  for (const [conceptName, conceptItems] of Object.entries(grouped)) {
    // Group header
    tableHtml += `
      <tr>
        <td colspan="6" style="background:#f5f5f5;padding:8px 12px;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:0.05em;color:#555;border-bottom:1px solid #ddd;">
          ${escapeHtml(conceptName)}
        </td>
      </tr>`;

    let groupTotal = 0;
    let groupHasPrice = false;

    for (const item of conceptItems) {
      rowIndex++;
      const price = item.selectedSupplier?.price ?? item.product.price_min ?? null;
      const lineTotal = price !== null ? price * item.quantity : null;
      if (lineTotal !== null) {
        groupTotal += lineTotal;
        groupHasPrice = true;
      }
      const bg = rowIndex % 2 === 0 ? "#fafafa" : "#fff";

      tableHtml += `
        <tr style="background:${bg};">
          <td style="padding:6px 12px;border-bottom:1px solid #eee;color:#888;font-size:11px;">${rowIndex}</td>
          <td style="padding:6px 12px;border-bottom:1px solid #eee;font-weight:500;">${escapeHtml(getProductName(item, lang))}</td>
          <td style="padding:6px 12px;border-bottom:1px solid #eee;color:#666;">${escapeHtml(item.product.category || "—")}</td>
          <td style="padding:6px 12px;border-bottom:1px solid #eee;text-align:center;">${item.quantity}</td>
          <td style="padding:6px 12px;border-bottom:1px solid #eee;text-align:right;">${price !== null ? `€${price.toFixed(2)}` : l.onRequest}</td>
          <td style="padding:6px 12px;border-bottom:1px solid #eee;text-align:right;font-weight:500;">${lineTotal !== null ? `€${lineTotal.toLocaleString("fr-FR", { minimumFractionDigits: 2 })}` : l.onRequest}</td>
        </tr>`;
    }

    // Group subtotal
    if (conceptItems.length > 1) {
      tableHtml += `
        <tr>
          <td colspan="5" style="padding:6px 12px;text-align:right;font-size:11px;font-weight:600;color:#555;border-bottom:2px solid #ddd;">${l.subtotal}</td>
          <td style="padding:6px 12px;text-align:right;font-weight:600;border-bottom:2px solid #ddd;">${groupHasPrice ? `€${groupTotal.toLocaleString("fr-FR", { minimumFractionDigits: 2 })}` : "—"}</td>
        </tr>`;
    }
  }

  const hasBudget = items.some(
    (i) => i.selectedSupplier?.price != null || i.product.price_min != null,
  );

  const notesSection = notes
    ? `
      <div style="margin-top:28px;">
        <h3 style="font-size:13px;font-weight:600;margin-bottom:8px;color:#333;">${l.notes}</h3>
        <p style="font-size:12px;color:#555;line-height:1.6;background:#f9f9f9;padding:12px;border-radius:4px;">${escapeHtml(notes)}</p>
      </div>`
    : "";

  const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <title>${l.title} — ${ref}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      font-size: 13px;
      color: #222;
      padding: 40px;
      max-width: 900px;
      margin: 0 auto;
    }
    @media print {
      body { padding: 20px; }
      .no-print { display: none !important; }
    }
    table { width: 100%; border-collapse: collapse; }
  </style>
</head>
<body>
  <!-- Header -->
  <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:32px;padding-bottom:20px;border-bottom:2px solid #222;">
    <div>
      <div style="font-size:24px;font-weight:800;letter-spacing:0.08em;color:#222;">TERRASSEA</div>
      <div style="font-size:10px;color:#888;letter-spacing:0.05em;margin-top:2px;">B2B OUTDOOR FURNITURE SOURCING</div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:16px;font-weight:600;color:#222;">${l.title}</div>
      <div style="font-size:11px;color:#888;margin-top:4px;">${l.ref}: ${ref}</div>
      <div style="font-size:11px;color:#888;">${l.date}: ${dateStr}</div>
    </div>
  </div>

  <!-- Client Info -->
  <div style="margin-bottom:28px;">
    <h3 style="font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.08em;color:#888;margin-bottom:10px;">${l.clientInfo}</h3>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:6px 24px;font-size:12px;">
      <div><span style="color:#888;">${l.name}:</span> <strong>${escapeHtml(formData.name || "—")}</strong></div>
      <div><span style="color:#888;">${l.company}:</span> <strong>${escapeHtml(formData.company || "—")}</strong></div>
      <div><span style="color:#888;">${l.email}:</span> ${escapeHtml(formData.email || "—")}</div>
      <div><span style="color:#888;">${l.phone}:</span> ${escapeHtml(formData.phone || "—")}</div>
    </div>
  </div>

  <!-- Product Table -->
  <div style="margin-bottom:28px;">
    <h3 style="font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.08em;color:#888;margin-bottom:10px;">${l.productTable}</h3>
    <table>
      <thead>
        <tr style="border-bottom:2px solid #222;">
          <th style="padding:8px 12px;text-align:left;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#888;width:36px;">${l.col_num}</th>
          <th style="padding:8px 12px;text-align:left;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#888;">${l.col_product}</th>
          <th style="padding:8px 12px;text-align:left;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#888;">${l.col_category}</th>
          <th style="padding:8px 12px;text-align:center;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#888;width:50px;">${l.col_qty}</th>
          <th style="padding:8px 12px;text-align:right;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#888;width:90px;">${l.col_unit_price}</th>
          <th style="padding:8px 12px;text-align:right;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#888;width:100px;">${l.col_total}</th>
        </tr>
      </thead>
      <tbody>
        ${tableHtml}
      </tbody>
    </table>
  </div>

  <!-- Budget Summary -->
  <div style="background:#f5f5f5;border-radius:6px;padding:16px 20px;margin-bottom:12px;">
    <div style="display:flex;justify-content:space-between;align-items:center;">
      <div>
        <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:0.05em;font-weight:600;">${l.totalEstimated}</div>
        <div style="font-size:24px;font-weight:700;color:#222;margin-top:2px;">
          ${hasBudget ? `~€${totalBudget.toLocaleString("fr-FR", { minimumFractionDigits: 2 })}` : "—"}
        </div>
      </div>
      <div style="text-align:right;font-size:12px;color:#666;">
        <div>${l.numProducts}: <strong>${items.length}</strong></div>
        <div>${l.numSuppliers}: <strong>${suppliersSelected}</strong></div>
      </div>
    </div>
  </div>
  <p style="font-size:10px;color:#aaa;text-align:center;margin-bottom:20px;">${l.exclVat}</p>

  ${notesSection}

  <!-- Footer -->
  <div style="margin-top:40px;padding-top:16px;border-top:1px solid #ddd;display:flex;justify-content:space-between;font-size:10px;color:#aaa;">
    <span>${l.footer}</span>
    <span>${dateStr}</span>
  </div>
</body>
</html>`;

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(html);
  printWindow.document.close();
  setTimeout(() => {
    printWindow.print();
  }, 500);
}
