
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS long_description text,
  ADD COLUMN IF NOT EXISTS collection text,
  ADD COLUMN IF NOT EXISTS dimensions_length_cm numeric,
  ADD COLUMN IF NOT EXISTS dimensions_width_cm numeric,
  ADD COLUMN IF NOT EXISTS dimensions_height_cm numeric,
  ADD COLUMN IF NOT EXISTS seat_height_cm numeric,
  ADD COLUMN IF NOT EXISTS weight_kg numeric,
  ADD COLUMN IF NOT EXISTS material_structure text,
  ADD COLUMN IF NOT EXISTS material_seat text,
  ADD COLUMN IF NOT EXISTS available_colors text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS country_of_manufacture text,
  ADD COLUMN IF NOT EXISTS warranty text,
  ADD COLUMN IF NOT EXISTS requires_assembly boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS maintenance_info text,
  ADD COLUMN IF NOT EXISTS uv_resistant boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS weather_resistant boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS fire_retardant boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS lightweight boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS easy_maintenance boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS customizable boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS dismountable boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS stock_status text DEFAULT 'available',
  ADD COLUMN IF NOT EXISTS stock_quantity integer,
  ADD COLUMN IF NOT EXISTS estimated_delivery_days integer,
  ADD COLUMN IF NOT EXISTS price_min numeric,
  ADD COLUMN IF NOT EXISTS price_max numeric,
  ADD COLUMN IF NOT EXISTS gallery_urls text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS documents jsonb DEFAULT '[]'::jsonb;
